version: "3.7"

services:
  
  bitcoin-core:
    container_name: bitcoin-core
    build:
        context: bitcoind
        args:
          LND_VER: $LND_VER
          ARCH: $ARCH
          BITCOIN_CORE_VERSION: $BITCOIN_CORE_VERSION 
    networks:
      - lnnet
    volumes:
      - $(PWD):/home/bitcoin/testnet
    expose:
      - "18333"
      - "18332"
      - "28332"
      - "28333"
    restart: always
      
  # ln-node:
  #   container_name: ln-node
  #   build:
  #       context: lnd
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always


  jupyter:
    build: 
      context: jupyter
    container_name: jupyter
    hostname: jupyter
    networks:
      - lnnet    
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/home/jovyan/work
      - ./volumes:/lnd_share
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    logging:
      driver: none
    
networks:
  lnnet:
    external: true