version: "3.7"

services:
  
  bitcoin-test:
    container_name: bitcoin-test
    user: 1000:1000
    build:
        context: bitcoind
        args:
          ARCH: $ARCH
          # ARCH: aarch64
          BITCOIN_CORE_VERSION: $BITCOIN_CORE_VERSION 
          # BITCOIN_CORE_VERSION: 22.0 
    networks:
      - lnnet
    volumes:
      - $PWD/bitcoind:/home/bitcoin/testnet
    expose:
      - "18333"
      - "18332"
      - "28332"
      - "28333"
    command: 
      - bitcoind
    restart: always 
    
  lnd-test:
      container_name: lnd-test
      image: lightninglabs/lnd:v0.14.2-beta@sha256:8318a24a3ad7319e424253eb56efcbf38e820ebc6d6b6edeec6a8a4e3e9314a0
      user: 1000:1000
      volumes:
        - ${PWD}/lnd:/data/.lnd
      environment:
        HOME: /data
      restart: on-failure
      stop_grace_period: 5m30s
      ports:
        - "9735:9735"
        - "$LND_REST_PORT:$LND_REST_PORT"
        - "$LND_GRPC_PORT:$LND_GRPC_PORT"
      networks:
        - lnnet
            
  # ln-node:
  #   container_name: ln-node
  #   build:
  #       context: lnd
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always


  # jupyter:
  #   build: 
  #     context: jupyter
  #   container_name: jupyter
  #   hostname: jupyter
  #   networks:
  #     - lnnet    
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebook:/home/jovyan/work
  #     - ./volumes:/lnd_share
  #   command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
  #   logging:
  #     driver: none
    
networks:
  lnnet: