version: "3.7"

networks:
  lnnet:

services:
  
  bitcoind-t:
    container_name: bitcoin-testnet
    build:
        context: bitcoind
    networks:
      - lnnet
    expose:
      - "19011" 
      - "19001"
      - "18333" # Bitcoin network protocol
      - "18332" # RPC
    volumes:
      - ${HD_PATH}:/data/.bitcoin
            
    restart: always

  # Alice:
  #   container_name: Alice
  #   build:
  #       context: lnd
  #   image: lnbook/lnd:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always

  # Bob:
  #   container_name: Bob
  #   build:
  #     context: c-lightning
  #   image: lnbook/c-lightning:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always

  # Chan:
  #   container_name: Chan
  #   build:
  #       context: eclair
  #   image: lnbook/eclair:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always

  # Dina:
  #   container_name: Dina
  #   build:
  #       context: lnd
  #   image: lnbook/lnd:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always
