version: "3.7"

services:
  
  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    restart: always
      
  alice:
    container_name: alice-ln
    build:
        context: lnd
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  bob:
    container_name: bob-ln
    build:
        context: lnd
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  chan:
    container_name: chan-ln
    build:
        context: lnd
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
  

  # jupyter:
  #   build: 
  #     context: jupyter
  #   container_name: jupyter
  #   hostname: jupyter
  #   networks:
  #     - lnnet    
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebook:/home/jovyan/work
  #     - ./volumes:/lnd_share
  #   command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
  #   logging:
  #     driver: none
    
networks:
  lnnet:
    external: true