version: "3.3"
networks:
  lnnet:

services:
  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    image: lnbook/bitcoind:latest
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    restart: always

  Alice:
    container_name: Alice
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  # Bob:
  #   container_name: Bob
  #   build:
  #     context: c-lightning
  #   image: lnbook/c-lightning:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always

  # Chan:
  #   container_name: Chan
  #   build:
  #       context: eclair
  #   image: lnbook/eclair:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always

  # Dina:
  #   container_name: Dina
  #   build:
  #       context: lnd
  #   image: lnbook/lnd:latest
  #   networks:
  #     - lnnet
  #   expose:
  #     - "9735"
  #   restart: always
