version: "3.7"

services:
                  
  bitcoin-test:
    container_name: bitcoin-test
    build:
        context: bitcoind
        args:
          ARCH: $ARCH
          BITCOIN_CORE_VERSION: $BITCOIN_CORE_VERSION     
    # volumes:
    #   - ./bitcoind:/home/bitcoin
    restart: on-failure
    ports:
      - "$BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT"
      - "$BITCOIN_RPC_PORT:$BITCOIN_RPC_PORT"
      - "$BITCOIN_ZMQ_RAWBLOCK_PORT:$BITCOIN_ZMQ_RAWBLOCK_PORT"
      - "$BITCOIN_ZMQ_RAWTX_PORT:$BITCOIN_ZMQ_RAWTX_PORT"
    networks:
      default:
        ipv4_address: $BITCOIN_IP

  lnd-alice:
      container_name: lnd-alice
      build:
        context: lnd
      restart: on-failure
      stop_grace_period: 5m30s
      ports:
        - "$LND_P2P_PORT:$LND_P2P_PORT"
        - "$LND_GRPC_PORT:$LND_GRPC_PORT"
      networks:
        default:
            ipv4_address: $LND_IP
  
  lnd-bob:
      container_name: lnd-bob
      build:
        context: lnd
      restart: on-failure
      stop_grace_period: 5m30s
      ports:
        - "$LND_P2P_PORT_B:$LND_P2P_PORT"
      networks:
        default:
            ipv4_address: $LND_IP_BOB
  
  lnd-charlie:
      container_name: lnd-charlie
      build:
        context: lnd
      restart: on-failure
      stop_grace_period: 5m30s
      ports:
        - "$LND_P2P_PORT_C:$LND_P2P_PORT"
      networks:
        default:
            ipv4_address: $LND_IP_CHARLIE
  
  pyclient:
    build: 
      context: pyclient
    container_name: pyclient
    ports:
      - "$JUPYTER_PORT:$JUPYTER_PORT"
    # volumes:
    #   - ./pyclient:/home/pyclient
    networks:
      default:
          ipv4_address: $PYC_IP
  
  
networks:
    default:
      name: lnnet
      ipam:
          config:
              - subnet: "$NETWORK_IP/24"
                gateway: "$GATEWAY_IP"
  